// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmivhwmjfdgndtblhyth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtaXZod21qZmRnbmR0YmxoeXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDM5NzEsImV4cCI6MjA1OTUxOTk3MX0.xbA2DhsEsCPuzF51QzSCwwUUkkQWLK7KF7rQarj2v8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);